.PHONY: clean All

All:
	@echo "==========Building project:[ Project_check - Debug ]=========="
	@cd "Project_check" && "$(MAKE)" -f  "Project_check.mk"
clean:
	@echo "==========Cleaning project:[ Project_check - Debug ]----------"
	@cd "Project_check" && "$(MAKE)" -f  "Project_check.mk" clean
