.PHONY: clean All

All:
	@echo "==========Building project:[ FirstProgram - Release ]=========="
	@cd "FirstProgram" && "$(MAKE)" -f  "FirstProgram.mk"
clean:
	@echo "==========Cleaning project:[ FirstProgram - Release ]----------"
	@cd "FirstProgram" && "$(MAKE)" -f  "FirstProgram.mk" clean
