.PHONY: clean All

All:
	@echo "==========Building project:[ WeeklyPay_Calcs - Release ]=========="
	@cd "WeeklyPay_Calcs" && "$(MAKE)" -f  "WeeklyPay_Calcs.mk"
clean:
	@echo "==========Cleaning project:[ WeeklyPay_Calcs - Release ]----------"
	@cd "WeeklyPay_Calcs" && "$(MAKE)" -f  "WeeklyPay_Calcs.mk" clean
